name: R-CMD-check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c('testthat', 'RSQLite', 'DBI'))
      - name: Run tests
        run: |
          Rscript -e "testthat::test_dir('tests/testthat')"
